package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Product;
import org.mybatis.cdi.Mapper;

// MyBatis DAO (data Access Object)
// MyBatis - duomenų susiejimo karkasas, kuris suteikia paprastą būdą atlikti
// duomenų bazės užklausas.  Sugeneruotas kodas skirtas nurodyti duomenų bazės operacijas,
// susijusias su prekių objektais. Kiekvienas metodas atitinka tam tikrą CRUD operaciją.
// Visi šie metodai suteikia patogią sasają, kuri leidžia lengvai valdyti duomenų bazės
// operacijas be tiesioginio SQL rašymo.

@Mapper
public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCT
     *
     * @mbg.generated Sun Mar 10 20:12:27 EET 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCT
     *
     * @mbg.generated Sun Mar 10 20:12:27 EET 2024
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCT
     *
     * @mbg.generated Sun Mar 10 20:12:27 EET 2024
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCT
     *
     * @mbg.generated Sun Mar 10 20:12:27 EET 2024
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCT
     *
     * @mbg.generated Sun Mar 10 20:12:27 EET 2024
     */
    int updateByPrimaryKey(Product record);
}